import { Facility, PromoTier, GalleryImage } from './types';

export const IMAGES = {
  heroBeachPath: '/images/hero_beach_path.jpg?v=real_v2',
  villaExterior: '/images/villa_exterior.jpg?v=real_v2',
  villaBedroom: '/images/villa_bedroom.jpg?v=real_v2',
  villaLiving: '/images/villa_living.jpg?v=real_v2',
  villaOutdoorDeck: '/images/villa_outdoor_deck.jpg?v=real_v2',
  villaSunset: '/images/villa_sunset.jpg?v=real_v2',
  villaBathroom: '/images/villa_bathroom.jpg?v=real_v2',
  villaBedroomMirror: '/images/villa_bedroom_mirror.jpg?v=real_v2',
  villaSignCloseup: '/images/villa_sign_closeup.jpg?v=real_v2',
  villaBeachPorch: '/images/villa_beach_porch.jpg?v=real_v2',
  villaBedroomDreamcatcher: '/images/villa_bedroom_dreamcatcher.jpg?v=real_v2',
  villaBunkBed: '/images/villa_bunk_bed.jpg?v=real_v2',
  villaKitchen: '/images/villa_kitchen.jpg?v=real_v2',
  villaEntry: '/images/villa_entry.jpg?v=real_v2',
  garden1: '/images/garden_1.jpg',
  garden2: '/images/garden_2.jpg',
  beach1: '/images/beach_1.jpg',
  beach2: '/images/beach_2.jpg',
  beach3: '/images/beach_3.jpg',
  beach4: '/images/beach_4.jpg',
  wave1: '/images/wave_1.jpg',
  wave2: '/images/wave_2.jpg',
  wave3: '/images/wave_3.jpg',
  wave4: '/images/wave_4.jpg',
  wave5: '/images/wave_5.jpg',
  wave6: '/images/wave_6.jpg',
  sunset1: '/images/sunset_1.jpg',
  sunset2: '/images/sunset_2.jpg',
  sunset3: '/images/sunset_3.jpg',
  sunset4: '/images/sunset_4.jpg',
  sunset5: '/images/sunset_5.jpg',
  sunset6: '/images/sunset_6.jpg',
  sunset7: '/images/sunset_7.jpg',
  sunset8: '/images/sunset_8.jpg',
  hamaraStory1: '/images/hamara_story_1.jpg',
  hamaraStory2: '/images/hamara_story_2.jpg',
  hamaraStory3: '/images/hamara_story_3.jpg',
  hamaraStory4: '/images/hamara_story_4.jpg',
  hamaraStory5: '/images/hamara_story_5.jpg',
  hamaraStory6: '/images/hamara_story_6.jpg',
  hamaraStory7: '/images/hamara_story_7.jpg',
  hamaraStory8: '/images/hamara_story_8.jpg',
  hamaraStory9: '/images/hamara_story_9.jpg',
};

export const GALLERY_IMAGES: GalleryImage[] = [
  {
    id: 'g1',
    src: IMAGES.villaExterior,
    alt: 'Hamara Guest House Premium Villa Exterior Entrance',
    category: 'Exterior',
    title: 'Modern Tropical Façade & Stone Pillars',
  },
  {
    id: 'g2',
    src: IMAGES.heroBeachPath,
    alt: 'Lush Garden Path Leading to Benawang Beach',
    category: 'Outdoor',
    title: 'Pathway to Benawang Beach',
  },
  {
    id: 'g3',
    src: IMAGES.villaBedroom,
    alt: 'Hamara Guest House Beautifully Renovated Master Bedroom with queen bed',
    category: 'Bedroom',
    title: 'Comfort Master Bedroom',
  },
  {
    id: 'g4',
    src: IMAGES.villaOutdoorDeck,
    alt: 'Covered Wooden Veranda and Dining Area',
    category: 'Outdoor',
    title: 'Spacious Wooden Veranda Deck',
  },
  {
    id: 'g5',
    src: IMAGES.villaLiving,
    alt: 'Bright Cozy Living Room with Smart TV, sofa and wooden bench',
    category: 'Living Area',
    title: 'Elegant Tropical Living Room',
  },
  {
    id: 'g6',
    src: IMAGES.villaSunset,
    alt: 'Golden Sunset View from Benawang Beach Krui',
    category: 'Sunset',
    title: 'Breathtaking Benawang Sunset',
  },
  {
    id: 'g7',
    src: IMAGES.villaBathroom,
    alt: 'Newly Renovated Bathroom with glass blocks and hot shower',
    category: 'Bathroom',
    title: 'Modern Tile Bathroom',
  },
  {
    id: 'g8',
    src: IMAGES.villaBedroomMirror,
    alt: 'AC Bedroom featuring full mirror wardrobe and stunning ocean waves painting',
    category: 'Bedroom',
    title: 'Mirrored Wardrobe AC Bedroom',
  },
  {
    id: 'g9',
    src: IMAGES.villaSignCloseup,
    alt: 'Closeup of Hamara Guest House custom wooden sign on stone pillar wall',
    category: 'Exterior',
    title: 'Villa Custom Wooden Signboard',
  },
  {
    id: 'g10',
    src: IMAGES.villaBeachPorch,
    alt: 'Gorgeous beachfront porch terrace dining table under wooden beams with seagrass lamps',
    category: 'Outdoor',
    title: 'Beachfront Porch Dining Table',
  },
  {
    id: 'g11',
    src: IMAGES.villaBedroomDreamcatcher,
    alt: 'Cozy AC Bedroom with dark gray bed setting and dreamcatcher ornament',
    category: 'Bedroom',
    title: 'Dreamcatcher Accent Bedroom',
  },
  {
    id: 'g12',
    src: IMAGES.villaBunkBed,
    alt: 'Spacious guest bedroom equipped with sturdy wooden bunk beds and fresh linen',
    category: 'Bedroom',
    title: 'Boho Wooden Bunk Beds',
  },
  {
    id: 'g13',
    src: IMAGES.villaKitchen,
    alt: 'Fully equipped modern kitchen with a round dining table, dark wood chairs, gas stove and refrigerator',
    category: 'Kitchen',
    title: 'Fully Equipped Guest Kitchen',
  },
  {
    id: 'g14',
    src: IMAGES.villaEntry,
    alt: 'Cozy entry foyer hallway with premium leather recliner chair, console table and vanity mirror',
    category: 'Living Area',
    title: 'Entry Hallway & Recliner Foyer',
  },
  {
    id: 'g15',
    src: IMAGES.garden1,
    alt: 'Lush green lawn and palm trees at Hamara Guest House',
    category: 'Garden',
    title: 'Beachfront Lawn & Garden 1',
  },
  {
    id: 'g16',
    src: IMAGES.garden2,
    alt: 'Beautiful manicured garden and tropical view',
    category: 'Garden',
    title: 'Ocean View Garden 2',
  },
  {
    id: 'g17',
    src: IMAGES.beach1,
    alt: 'Stunning white sandy beach and clear ocean at Hamara Guest House',
    category: 'Beach',
    title: 'Pristine Beach Shoreline 1',
  },
  {
    id: 'g18',
    src: IMAGES.beach2,
    alt: 'Beautiful blue sky and turquoise water at Benawang Beach',
    category: 'Beach',
    title: 'Crystal Clear Beach 2',
  },
  {
    id: 'g19',
    src: IMAGES.beach3,
    alt: 'Dreamy tropical coconut palms lining Benawang Beach',
    category: 'Beach',
    title: 'Tropical Palm Beach 3',
  },
  {
    id: 'g20',
    src: IMAGES.beach4,
    alt: 'Relaxing sandy shores of Benawang Beach in Krui',
    category: 'Beach',
    title: 'Serene Coastal Beach 4',
  },
  {
    id: 'g21',
    src: IMAGES.sunset1,
    alt: 'Gorgeous golden sunset reflecting on the sea at Hamara',
    category: 'Sunset',
    title: 'Sunset Palette 1',
  },
  {
    id: 'g22',
    src: IMAGES.sunset2,
    alt: 'Breathtaking evening sky over Benawang Beach',
    category: 'Sunset',
    title: 'Sunset Palette 2',
  },
  {
    id: 'g23',
    src: IMAGES.sunset3,
    alt: 'Silhouetted palm trees during sunset at Hamara',
    category: 'Sunset',
    title: 'Sunset Palette 3',
  },
  {
    id: 'g24',
    src: IMAGES.sunset4,
    alt: 'Warm amber glow of sunset over the waves in Krui',
    category: 'Sunset',
    title: 'Sunset Palette 4',
  },
  {
    id: 'g25',
    src: IMAGES.sunset5,
    alt: 'Peaceful sunset ambiance at Hamara Guest House',
    category: 'Sunset',
    title: 'Sunset Palette 5',
  },
  {
    id: 'g26',
    src: IMAGES.sunset6,
    alt: 'Dramatic colors of evening sunset at Benawang Beach',
    category: 'Sunset',
    title: 'Sunset Palette 6',
  },
  {
    id: 'g27',
    src: IMAGES.sunset7,
    alt: 'Scenic twilight sky and gentle waves',
    category: 'Sunset',
    title: 'Sunset Palette 7',
  },
  {
    id: 'g28',
    src: IMAGES.sunset8,
    alt: 'Last light of the day at the beachfront',
    category: 'Sunset',
    title: 'Sunset Palette 8',
  },
  {
    id: 'g29',
    src: IMAGES.wave1,
    alt: 'Magnificent rolling surf waves in Krui',
    category: 'Waves',
    title: 'Gulungan Ombak 1',
  },
  {
    id: 'g30',
    src: IMAGES.wave2,
    alt: 'Beautiful clear ocean waves breaking on the reef',
    category: 'Waves',
    title: 'Gulungan Ombak 2',
  },
  {
    id: 'g31',
    src: IMAGES.wave3,
    alt: 'Crisp turquoise wave crested under bright sunlight',
    category: 'Waves',
    title: 'Gulungan Ombak 3',
  },
  {
    id: 'g32',
    src: IMAGES.wave4,
    alt: 'Perfect surfing waves at Krui point break',
    category: 'Waves',
    title: 'Gulungan Ombak 4',
  },
  {
    id: 'g33',
    src: IMAGES.wave5,
    alt: 'Powerful swell forming pristine ocean waves',
    category: 'Waves',
    title: 'Gulungan Ombak 5',
  },
  {
    id: 'g34',
    src: IMAGES.wave6,
    alt: 'Dynamic ocean waves in the greater Krui region',
    category: 'Waves',
    title: 'Gulungan Ombak 6',
  },
  {
    id: 'g35',
    src: IMAGES.hamaraStory1,
    alt: 'Hamara Guest House brand story chapter 1',
    category: 'Hamara Story',
    title: 'Hamara Story 1',
  },
  {
    id: 'g36',
    src: IMAGES.hamaraStory2,
    alt: 'Hamara Guest House brand story chapter 2',
    category: 'Hamara Story',
    title: 'Hamara Story 2',
  },
  {
    id: 'g37',
    src: IMAGES.hamaraStory3,
    alt: 'Hamara Guest House brand story chapter 3',
    category: 'Hamara Story',
    title: 'Hamara Story 3',
  },
  {
    id: 'g38',
    src: IMAGES.hamaraStory4,
    alt: 'Hamara Guest House brand story chapter 4',
    category: 'Hamara Story',
    title: 'Hamara Story 4',
  },
  {
    id: 'g39',
    src: IMAGES.hamaraStory5,
    alt: 'Hamara Guest House brand story chapter 5',
    category: 'Hamara Story',
    title: 'Hamara Story 5',
  },
  {
    id: 'g40',
    src: IMAGES.hamaraStory6,
    alt: 'Hamara Guest House brand story chapter 6',
    category: 'Hamara Story',
    title: 'Hamara Story 6',
  },
  {
    id: 'g41',
    src: IMAGES.hamaraStory7,
    alt: 'Hamara Guest House brand story chapter 7',
    category: 'Hamara Story',
    title: 'Hamara Story 7',
  },
  {
    id: 'g42',
    src: IMAGES.hamaraStory8,
    alt: 'Hamara Guest House brand story chapter 8',
    category: 'Hamara Story',
    title: 'Hamara Story 8',
  },
  {
    id: 'g43',
    src: IMAGES.hamaraStory9,
    alt: 'Hamara Guest House brand story chapter 9',
    category: 'Hamara Story',
    title: 'Hamara Story 9',
  },
];

export const FACILITIES: Facility[] = [
  {
    id: 'f1',
    title: '3 AC Bedrooms',
    description: 'Beautifully appointed bedrooms with modern, quiet air conditioning to guarantee a restful sleep.',
    icon: 'Bed',
  },
  {
    id: 'f2',
    title: 'Hot Shower & Bathroom',
    description: 'Freshly renovated, modern bathroom equipped with strong pressure hot water shower.',
    icon: 'ShowerHead',
  },
  {
    id: 'f3',
    title: 'Fully Equipped Kitchen',
    description: 'Complete cooking amenities including gas stoves, cutlery, and a large double-door refrigerator.',
    icon: 'Utensils',
  },
  {
    id: 'f4',
    title: 'StarLink Ultra-WiFi',
    description: 'High-speed satellite internet, perfect for remote workers, digital nomads, or streaming.',
    icon: 'Wifi',
  },
  {
    id: 'f5',
    title: 'Smart TV Entertainment',
    description: 'Wide-screen Smart TV set up with streaming apps for cozy movie nights after long surf sessions.',
    icon: 'Tv',
  },
  {
    id: 'f6',
    title: 'Exclusive Garden Area with Ocean Views',
    description: 'A private, manicured tropical natural lawn and garden with beautiful ocean views, exclusive for villa guests.',
    icon: 'Trees',
  },
  {
    id: 'f7',
    title: 'Anjungan Cooking Area',
    description: 'Outdoor traditional pavilion cooking facilities, custom-built and ideal for long-stay guests.',
    icon: 'ChefHat',
  },
  {
    id: 'f8',
    title: 'Outdoor Dining & Shower',
    description: 'A spacious wooden dining table on the deck and a fresh outdoor shower to rinse off beach sand.',
    icon: 'Sun',
  },
];

export const PROMO_TIERS: PromoTier[] = [
  {
    id: 'p1',
    nightsRequired: 2,
    title: 'Weekend Explorer Reward',
    discountPercent: 5,
    freeNights: 0,
    description: 'Perfect for domestic weekend getaways.',
    benefits: ['5% Discount off entire stay', 'Dedicated on-site staff assistance'],
  },
  {
    id: 'p2',
    nightsRequired: 4,
    title: 'Sumatran Surf & Swim Week',
    discountPercent: 10,
    freeNights: 0,
    description: 'For surfers and families looking to settle in.',
    benefits: [
      '10% Discount off entire stay',
      'Professional housekeeping every 2 days',
      'Exclusive 15:00 access to Sumatra’s best luxury pool nearby',
    ],
  },
  {
    id: 'p3',
    nightsRequired: 7,
    title: 'Tropical Extended Escape',
    discountPercent: 0,
    freeNights: 1,
    description: 'Pay for 6 nights, get the 7th night absolutely FREE!',
    benefits: [
      '1 Night completely FREE (Pay for 6, Stay 7)',
      'Professional housekeeping every 2 days',
      'Daily Sumatra luxury pool access starting 15:00',
    ],
  },
];

export const TESTIMONIALS = [
  {
    id: 't1',
    name: 'Marcus & Sophie',
    role: 'Surfers & Nomads from Australia',
    text: 'Hamara is a hidden gem in Pugung Walur! Having ultra-fast StarLink internet while living literally steps from the beach is a dream. The garden path directly leads to Benawang beach. We will definitely come back!',
    rating: 5,
  },
  {
    id: 't2',
    name: 'Keluarga Rahardjo',
    role: 'Family from Jakarta',
    text: 'Sangat puas menginap di Hamara. Kamar tidurnya bersih, AC dingin, dan dapurnya lengkap sekali. Anak-anak sangat suka bermain di kebunnya yang luas dan bersih. Sangat direkomendasikan untuk liburan keluarga di Krui.',
    rating: 5,
  },
  {
    id: 't3',
    name: 'Yuki Takahashi',
    role: 'Adventure Traveler from Japan',
    text: 'The best villa quality in the entire Pugung Krui area, without question. Clean, premium materials, and superb hospitality. The staff helped us with everything, and we loved their beach cleaning initiative to keep Pugung plastic-free.',
    rating: 5,
  },
];
